# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.209
neo_version_range=[21,)
loader_version_range=[4,)
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
mod_id=foodnerf
mod_name=foodnerf
mod_license=MIT
mod_version=1.2.2
mod_group_id=net.schn4beltier
mod_authors=schn4beltier
mod_description=
